### ISSUE TITLE
Implementing all the functionalities of HTTP/3

### ISSUE THREAD

**Issue by redoriental** [BiagioFesta/wtransport#11]

**Comment by BiagioFesta** [comment]
This crate focus on WebTransport protocol.

Although most of the HTTP3 standard protocol is implemented in `wtransport-proto`, this library will focus on part of HTTP3 that matters for WebTransport.

For example, HTTP request/reply are not implemented beside the `CONNECT` method.

What is still missing here, that I am planning to implement, is the ability to retrieve `CONNECT` client request path. I am going to open an issue as soon as I have time to work on it
