### ISSUE TITLE
Add client API and example for connecting to self signed server via `serverCertificateHashes`

### ISSUE THREAD

**Issue by TheButlah** [BiagioFesta/wtransport#128]
Use case:
I am building an application that will use wtransport on native clients and the web apis on browser clients. Servers are self hosted by players and ephemeral, meaning that I can't expect them to have valid domains to issue LetsEncrypt certs to. Instead I am relying on the [serverCertificateHashes](https://www.w3.org/TR/webtransport/#dom-webtransportoptions-servercertificatehashes) feature the browser apis expose to bypass public key infrastructure, and I send the digest instead via other out-of-band mechanisms (which themselves are signed and have a web-of-trust approach).

I don't see a way to construct a `wtransport` client that uses these self-signed keys, unless I fully disable tls checks via the dangerous [`with_no_cert_validation`](https://docs.rs/wtransport/latest/wtransport/config/struct.ClientConfigBuilder.html#method.with_no_cert_validation) option.

How can I create a client that allowlists a particular self-signed certificate hash a-la `serverCertificateHashes`?

**Comment by BiagioFesta** [comment]
Hi,

Today, `wtransport` should already provide a way to cover your use case.

In particular, `wtransport` exposes TLS configuration backed by `rustls`. When creating your `wtransport` client configuration, a custom TLS configuration can be set with [with_custom_tls](https://docs.rs/wtransport/latest/wtransport/config/struct.ClientConfigBuilder.html#method.with_custom_tls). This allows you to fully customize the TLS layer.

`rustls::ClientConfig` allows you to create a custom certificate validator using [set_certificate_verifier](https://docs.rs/rustls/0.21.10/rustls/client/struct.DangerousClientConfig.html#method.set_certificate_verifier).

A verifier is quite easy to implement, and you can place the custom logic for certificate validation here.

Inside `wtransport`, the same mechanism is used to create a `NoCertVerifier`. You can have a look [here](https://github.com/BiagioFesta/wtransport/blob/master/wtransport/src/config.rs#L716-L718).

Of course, in your case, your verifier can simply check against hashes.

---

Having said that, I am curious about the use case. I am wondering if the application is self-hosted, `with_no_cert_validation` should not have security implications (if machine-local).

Moreover, your feedback makes me wonder if `wtransport` might expose some wrapper around that to emulate the `serverCertificateHashes`.

Feel free to ask if something is not clear or if you need more information.

Thank you for your feedback.

**Comment by BiagioFesta** [comment]
Additional tips you might need:
* `wtransport` re-export `rustls` with the correct version. You should be able to get access to `rustls` directly via `wtransport::tls::rustls` [See doc here](https://docs.rs/wtransport/latest/wtransport/tls/index.html).
* When creating a custom TLS layer, you should remember to set the correct ALPN. [See here](https://github.com/BiagioFesta/wtransport/blob/master/wtransport/src/config.rs#L749-L758). It is just a "binary string". [See here](https://docs.rs/wtransport-proto/0.1.10/wtransport_proto/constant.WEBTRANSPORT_ALPN.html)

**Comment by TheButlah** [comment]
`expose some wrapper around that to emulate the serverCertificateHashes.`

adding that to the builder would definitely be useful!

**Comment by BiagioFesta** [comment]
Before modifying `wtransport` interface, I would like to better understand the possible usage and use case.

Asking because W3C [`serverCertificateHashes`](https://www.w3.org/TR/webtransport/#dom-webtransportoptions-servercertificatehashes) has some security concerns and forces some constraints. 
For example: 
> [...] the total length of the validity period MUST NOT exceed two weeks.

**Comment by TheButlah** [comment]
I would expect that because this is a helper function, the constraints on the native api match the constraints on the browser api.

In my case, I am using wtransport because I want my game to support web clients. Therefore I want my native clients and web clients to work similarly (so I don't find out later down the line that I'm doing something on native that is prevented in the browser apis).

**Comment by BiagioFesta** [comment]
I've opened a PR: https://github.com/BiagioFesta/wtransport/pull/131

If you want to have a look and provide some feedback. Thanks
