### ISSUE TITLE
Implement AsyncRead + AsyncWrite for bidirectional stream as a single type.

### ISSUE THREAD

**Issue by TheButlah** [BiagioFesta/wtransport#134]
Hi, I'm trying to use `tokio_util::codec` to introduce framing on top of the wtransport byte streams. Several helper functions in tokio_util are only impleented on a single io type T, that implements *both* async read and async write. 

Because wtransport returns (SendStream, RecvStream) instead of a single type, it complicates using these helper functions, as I would have to introduce my own helper type to join together the sender and receiver.

Is there a reason under the hood why these types cannot be expressed as a single read/write type instead of a tuple? Maybe it was to unify the types with the unidirectional stream? (if that is the case, there can be a `.split()` function on this joined type that turns it into the two streams).

Side note: calling them streams is a bit confusing, because they implement AsyncWrite/Read rather than Stream or Sink. (Edit: I guess this was done because the webtransport api calls them streams).

**Comment by BiagioFesta** [comment]
Hi,

The general idea is to follow the same approach used in the underlying QUIC library which makes sense to me.

With this approach only 2 types are requires (`SendStream` and `RecvStream`) providing simple and immediate API. They are 2 very well defined objects providing the 2 different functionalities (send and receive), single-responsibility principle.

Other libraries might introduce composite types. For example, `s2n-quic`, another QUIC library, uses multiple types and stream-functions: https://docs.rs/s2n-quic/latest/s2n_quic/connection/struct.Connection.html# 
Multiple `accept_*` function with `enum` variants.

---

> Maybe it was to unify the types with the unidirectional stream? (if that is the case, there can be a .split() function on this joined type that turns it into the two streams).

Indeed, this is true as well. I would avoid having `UnidirectionalRecv`, `UnidirectionalSend` and `Bidirectional` (for a total of 3 types) where `Bidirectional` overlaps code/functionalities.

However, I am not sure understanding your suggestion. How `split` works with *unidirectional* stream? (I would imagine `split` for *bidirectional*).

---

Moreover, current `SendStream` and `RecvStream` can be easily composable. I reckon you mentioned this, but I don't see how this might be complicated.

```
pub struct BiStream((SendStream, RecvStream));

impl AsyncRead BiStream { ... }

impl AsyncWrite BiStream { ... }
```

Maybe you can provide some code example also here, so we can see if we can find a better solution providing some helpers directly in `wtransport`.

---

> Side note: calling them streams is a bit confusing, because they implement AsyncWrite/Read rather than Stream or Sink. (Edit: I guess this was done because the webtransport api calls them streams).

Yeah :)

This is a little bit inconvenient, but QUIC works with [`Streams`](https://datatracker.ietf.org/doc/html/rfc9000#name-streams).

**Comment by BiagioFesta** [comment]
Is this might help: https://github.com/BiagioFesta/wtransport/pull/135?
