### ISSUE TITLE
Question on writing data and flushing

### ISSUE THREAD

**Issue by jin-eld** [BiagioFesta/wtransport#145]
Hi,

I hope it's OK to also just ask questions here, I did not see a mailing list or a discussions section anywhere  :)

I am implementing a client and server application using the `wtransport` crate and I noticed a certain behavior where I am not sure if something does not work as it should or if my idea of how I use `wtransport` is not correct.

In short, the problem I am seeing is that when the client calls `writer.write_all(&fixed_size_buffer).await` 128 number of times and stops, while the server is expecting to `reader.read_exact(&mut same_sized_buffer).await` the same number of times into a buffer of the same size, the server will not receive the buffer 128 times, but the loop calling `read_exact()` will block after 113 or 114 iterations without getting more data.

Only if the client calls `writer.finish().await`, then the server will receive everything, i.e. `read_exact()` will be called 128 times as expected. However, I am not looking to terminate the stream, since after a pause I would like to send more data.

I do not see a `flush()` method which could possibly help in such a situation, so I wonder - what is the "correct" way to handle such a scenario?

Should I not be using `write_all()`, but `write_chunk()` instead? What is the difference between these two functions anyway (except for the type of the buffer parameter)?

Kind regards,
Jin

**Comment by BiagioFesta** [comment]
> I hope it's OK to also just ask questions here, I did not see a mailing list or a discussions section anywhere :)

It's totally OK asking question here (we have a issue-label specifically for this kind). However, if you prefer we also have a discord server (check out the `README.md`); however, I am not real fan of discord (being close source) and I might not be daily available there.

---

You assumption is correct. WebTransport streams are reliable transmission channels, and, similarly to TCP, data are guaranteed to arrive to the peer.

Hard to do an investigation, as it might depend on the code. My guess: is it possible that your client program ends/closes? Asking because if the webtransport connection is terminated, then delivery of data on unfinished streams is not guaranteed.

(It also would be great if you can provide a MRE -minimal reproducible example-)

Thank you

**Comment by BiagioFesta** [comment]
Careful that `thread sleep()` is generally not a good thing.

Assuming you are using `tokio` runtime, you should use [`sleep(...).await`](https://docs.rs/tokio/latest/tokio/time/fn.sleep.html). If instead you use `std::thread::sleep` you are actually blocking the runtime worker (no other tasks can run), as you are not yielding the control flow

**Comment by jin-eld** [comment]
> Careful that `thread sleep()` is generally not a good thing.

Ooh, I did not think of that. This explains why adding a sleep did not help... However, adding a `read()` and expecting an ack byte from the server did the trick. I can not reproduce the issue with the native client and server anymore.

I can however reproduce it with a WASM client, however at this point I am inclined to believe that the issue may be in `web_sys` and not in `wtransport`...

With WASM it seems that either data gets corrupted or perhaps lost when sent from the client to the server, because at some point I start getting values which I do not expect to receive.


I did upload the example code here:
https://github.com/jin-eld/webtransport-issue-reproducer

Question is, if there is a more or less simple way to check if we are dealing with some incompatibility between `web_sys::WebTransport` which is marked as an unstable API and `wtransport`, bad coding on my side or if it is a bug in one of the components (perhaps even the browser?).

**Comment by BiagioFesta** [comment]
By a quick glance, the server seems to be ok. Only, I'd avoid `unsafe`, especially for a repr example (you can just allocated a buffer with vector `vec![0; CHUNK_SIZE_BYTES]`)

To me, it feels more like a datarace, as if I slow down the wasm client then it seems to work

**Comment by jin-eld** [comment]
> By a quick glance, the server seems to be ok. Only, I'd avoid unsafe, especially for a repr example (you can just allocated a buffer with vector vec![0; CHUNK_SIZE_BYTES])

In my actual app I am reusing the same buffer again and again in various places and I was not able to figure out how to do that using `read_exact()`, because it looks at the length and not at the capacity and the only way to set the length without filling up the buffer was to take the `unsafe` route. I am new to Rust and this is totally offtopic here, but if you'd hint me on how to do it properly I'd highly appreciate it, so far I was not able to figure it out :P

> To me, it feels more like a datarace, as if I slow down the wasm client then it seems to work

Actually, sorry, I totally forgot to mention that, in my application, when I enable trace debug logs in the server which makes the wtransport and the quinn crates very chatty and thus slows everything down due to excessive console logs - then the problem went away without any change on the WASM client side.

So, you mean - data race in `web_sys`?

**Comment by BiagioFesta** [comment]
> So, you mean - data race in `web_sys`?

Hard to say, it requires a deep debugging session. Maybe you can try to write the exact same client login in pure javascript instead of rust and check if the behavior is the same?

**Comment by jin-eld** [comment]
> Maybe you can try to write the exact same client in pure Javascript instead of Rust and check whether the behavior is the same?

Turned out - it is indeed the same, the issue is reproducible with a JS client as well:
https://github.com/jin-eld/webtransport-issue-reproducer/blob/master/www/jsclient.html

I am not much of a JS guy, so I did not implement any exception handling or detailed error checks, expecting it to crash on errors which is OK for this demo. The client console.logs all 128 chunks as being sent and fails to read an ack, while the server receives lesser chunks and gets the termination byte too early. So it seems, also with a native JS client some packets get lost along the way...

I am not entirely sure what this means though: buggy browser implementation? Or an issue in `wtransport`? Could still be either one...

**Comment by BiagioFesta** [comment]
I have changed the client logic to sending chunks formatted like:
```
|  byte 0: CHUNK ID | 0..... | TERMINATION |
```
(So the chunk has a counter on first byte, all zeros, and the termination byte)


The server receives:
```
Received chunk id: 0
Received chunk id: 1
Received chunk id: 12
Received chunk id: 13
...
```

Like somehow some chunks are not sent by the client.

I have confirmed that by inspecting the network. 
![image](https://github.com/BiagioFesta/wtransport/assets/15035284/38439402-6977-40c3-99e2-d9e4405033ff)

On the QUIC stream, we got the byte `0x0c` (i.e., the beginning of chunk id 12) at QUIC stream offset `131075`.

```
// We need to remove 3 bytes due to WebTransport header on the stream.
131075 - 3 byte = 131072 

// We need to remove 2 bytes sent by the application protocol as NUM of CHUNKS
131072 - 2 bytes = 131070 
```

And thus: `131072 / 65535 = 2`

This confirms that the chunk starting with byte `0x0c` is at the third iteration of sent chunks. In fact, the chunks `2, 3, 4, ..., 11` are not sent by the client.

**Comment by jin-eld** [comment]
Oh wow, thank you for looking into this!

So far I failed to convince Firefox to connect to the server. I created the certificate, added it to the system store, imported it in the authority tab in FF and also told FF to accept it when asked. Pointed the webserver to it and also loaded the certificate and the key in the Rust wtransport-server.

However, in Rust I get: `connection aborted by peer: the cryptographic handshake failed: error 42` while in Firefox I see `message: "WebTransport connection rejected"`

Not sure what I am missing, will try again tomorrow....

**Comment by jin-eld** [comment]
So, after sorting out the certificate issue and getting it to run in Firefox it seems that this is a Chromium bug.

In Firefox both, the WASM client as well as the JS client work without issues.

There is a somewhat similar bug in the Chromium issue tracker:
https://issues.chromium.org/issues/326887753

I'll post my findings and the link to the reproducer there.

As for this `wtransport` specific question - I think we can close it, thank you very much for helping out and debugging!

**Comment by jin-eld** [comment]
We added our info in https://issues.chromium.org/issues/326887753 and also linked the github issue.
If we will be asked to open a separate issue, I'll link it here as well.
