### ISSUE TITLE
I believe you don't need to set authentication. Just provide the information to the user and let them handle the operations.

### ISSUE THREAD

**Issue by redoriental** [BiagioFesta/wtransport#15]

**Comment by BiagioFesta** [comment]
What do you mean "authentication"? TLS stack?
Can you provide an example and a complete description of the issue?

**Comment by redoriental** [comment]
use std::io::Read;
use std::net::SocketAddr;
use std::ops::Deref;
use std::ptr::null;
use std::sync::{Arc, Mutex};
use std::time::Duration;
use wtransport::tls::Certificate;
use wtransport::Endpoint;
use wtransport::ServerConfig;
use tokio;
use tokio::io::AsyncReadExt;
use tokio::time::timeout;
use wtransport::datagram::Datagram;

#[tokio::main]
async fn main() {
    let config = ServerConfig::builder()
        .with_bind_address(SocketAddr::new("127.0.0.1".parse().unwrap(), 10001))
        .with_certificate(
            Certificate::load(
                r"C:\Users\redoriental\Downloads\test2\redoriental.top.crt",
                r"C:\Users\redoriental\Downloads\test2\redoriental.top8.key",
            )
                .unwrap(),
        )
        .keep_alive_interval(Some(Duration::from_secs(10000)))
        .build();
    // let timeout_duration = Duration::from_micros(5);
    let server = Endpoint::server(config).unwrap();
    loop {
        println!("Waiting for incoming connection...");
        let connection = Arc::new(server.accept().await.unwrap().await.unwrap());
        let path = connection.path(); //https://..../path
        let map:std::collections::hash_map = connection.attribute();// https://....?a=b&b=c
        //Let the user handle it here, rather than you imposing limitations.
        tokio::spawn(async move {
            loop {
                tokio::select! {
                    bid_stream = connection.accept_bi()=>{
                        let bid_stream = bid_stream.unwrap();
                        let mut send_stream =  bid_stream.0;
                        let mut recv_stream = bid_stream.1;
                        tokio::spawn(async move{
                            let mut buffer = [0; 65536];
                            loop{
                                let bytes_read = recv_stream.read(&mut buffer).await.unwrap().unwrap();
                                send_stream.write(&buffer[..bytes_read]).await;
                            }
                        });
                    }
                uni_stream = connection.accept_uni()=>{
                    let us = Arc::new(uni_stream.unwrap());
                    tokio::spawn(async move{
                        let us = us.clone();
                        loop{

                        }
                    });
                }
                dgram = connection.receive_datagram()=>{
                        let data = dgram.unwrap();
                        connection.send_datagram(data.as_ref());
                    }
            }
            }
        });
    }
}
