### ISSUE TITLE
Allow assigning fields at `ClientConfig`

### ISSUE THREAD

**Issue by MOZGIII** [BiagioFesta/wtransport#173]
I would like to implement a flow of operations with `wtransport` where most of the parts of `ClientConfig` are initialized at one place, but some are initialized in the other place - much later. I also want to do that without writing boilerplate code to hold all the partially-initialized `ClientConfig` values.

In particular - I need to specify which SHA-256 hashes are allowed after the initial initialization is done - however, the current implementation of the `ClientConfig` API family does not allow that.

Note that can't simply take the `ClientConfigBuilder` and call `with_server_certificate_hashes` later without keeping all the rest of builder params around somewhere as well - as the order of the builder calls is not flexible.

This API is clearly inspired by the `rustls`, which doesn't suffer from this issue because it simply has an open struct, the fields which could be assigned after the builder completes - or without the use of the builder API at all, and also provides explicit escape hatches for when the private fields needs to be assigned.

The existing options - like simply keeping custom code to wrap around the desired fields of the `ClientConfig` and do a delayed initialization is quite unergonomic - firstly, this is a crate, and I don't need to have the troubles of changing *my API* when the *`ClientConfig` fields/builder* changes - I would much rather delegate the `wtransport` settings that I don't need to concern myself with to the original `ClientConfig` type, and only assign the field I need to (TLS verifier in this case). In addition - the `ServerHashVerification` is not public, so I simply can't construct it via any other way but via the builder.

What would work for me, in this particular scenario, in some tweaking of the `ServerHashVerification` to allow updating the certificate hashes down the line. It also helps for changing the hashes to newer ones while at runtime - creating a new `ClientConfig` and swapping it at the existing `Endpoint` (or creating a new one) is often unergonomic for the same concerns as above - that part of the code does not usually want to concern itself with everything it takes to build a `ClientConfig` from scratch - just doing it's specific thing, which is to update the hashes.

**Comment by BiagioFesta** [comment]
The builder API is a common well-known rust-idiomatic pattern: [FYI](https://rust-unofficial.github.io/patterns/patterns/creational/builder.html).

---

Closing this issue, as invalid.

Currently: [this is wtransport::ClientConfig](https://github.com/BiagioFesta/wtransport/blob/2d5ba76fd02040abbb48a6f5f544d96595d0c7eb/wtransport/src/config.rs#L550-L555):
```
pub struct ClientConfig {
    pub(crate) bind_address: SocketAddr,
    pub(crate) dual_stack_config: Ipv6DualStackConfig,
    pub(crate) quic_config: QuicClientConfig,
    pub(crate) dns_resolver: Box<dyn DnsResolver + Send + Sync + Unpin>,
}
```

(as you can notice, it does not store any TLS configuration).

The field you want to publicly access is `quic_config` (which contains the TLS configuration), and it is already publicly accessible via `quic_config[_mut]` method.

Therefore, strictly speaking, as per this particular request of yours (`Allow assigning fields at ClientConfig`), that's already possible (ignoring `bind_address` which is a trivial-`Copy` you can easily keep track of it).

**Comment by MOZGIII** [comment]
Well, closing this might be jumping the gun: how would you propose I do this right now? Yes, I can set the server certificate verifier - but I can't create a new `ServerHashVerification` directly, only through via the builder.

Technically, the subject of the issue is invalid, but I'd rather rename and reopen this issue than create a new one. I can, of course, leave it be if you're not interested in investigating this further - just let me know. I did create quite a few issues here lately - but I do actually have a lot of issues, honestly, not trying to annoy you or anything like that.

**Comment by BiagioFesta** [comment]
Not annoying at all. I appreciate feedback.

Today I had a few minutes extra to dedicate to inbox and I processed some of those pending items, cleaning up.

I closed this one as, as per title, is technically solved.

`ClientConfig` does not store TLS configuration at all, and changing that would require reworking the entire module which is, at the moment, not worth it.

Concerning your hash update issue instead, the easiest workaround is to access the quic config and push a new one with the new TLS configuration. However, in order to do that, you need to instantiate the server certificate hashes cert verifier on your own (which is a request already tracked: https://github.com/BiagioFesta/wtransport/issues/169)
