### ISSUE TITLE
Update the timeout for a specific client/SocketAddr at runtime

### ISSUE THREAD

**Issue by cBournhonesque** [BiagioFesta/wtransport#184]
I have a case where some clients stop sending packets because they are running in a browser tab that has been throttled.
I believe this could cause the webtransport connection to timeout.

I'm wondering if it's possible to update the timeout for an 'idle connection', as described in https://github.com/w3c/p2p-webtransport/issues/106

**Comment by BiagioFesta** [comment]
Are you referring [Config::max_idle_timeout](https://docs.rs/wtransport/latest/wtransport/config/struct.ClientConfigBuilder.html#method.max_idle_timeout) & [Config::keep_alive_interval](https://docs.rs/wtransport/latest/wtransport/config/struct.ClientConfigBuilder.html#method.keep_alive_interval)?

**Comment by cBournhonesque** [comment]
Yes.

I actually found another solution for my problem; but out of curiosity is it possible to update those settings even after the connection has been established?

**Comment by BiagioFesta** [comment]
> but out of curiosity is it possible to update those settings even after the connection has been established?

No, it is not.

The underlying QUIC transport does not allow that. For example, [max_idle_timeout](https://datatracker.ietf.org/doc/html/rfc9000#name-transport-parameter-definit) is a QUIC transport parameters which is exchanged during connection establishment

**Comment by cBournhonesque** [comment]
Thank you!
