### ISSUE TITLE
When the connection is in a waiting state, sending data packets may not be possible.

### ISSUE THREAD

**Issue by redoriental** [BiagioFesta/wtransport#19]

**Comment by BiagioFesta** [comment]
Can you please fill a description of the issue?

The issue is not clear. For example:
- Connection is in a waiting state? What do you mean here?

If it is possible, it would be great if you can provide a reproducible example. E.g., some steps to reproduce the issue.

**Comment by redoriental** [comment]
In one thread, within tokio:select! { data = connection.recvdatagram => {} }, another thread cannot use connection.sendDatagram(data)

**Comment by BiagioFesta** [comment]
First of all, I have a couple of questions.

It seems you are using `tokio` for async rust-runtime, but, at the same time, you are using process-"threads". 

> another thread

Generally, threads are not meant to be mixed within a tokio program.
Do you mean "another 'tokio' task"? (E.g., `tokio::spawn`).

---

Having said that,
I tried to reproduce, but unsuccessfully. Here is a snippet of my test (with threads):



```
// `server` is wtransport::Endpoint
let incoming_request = server.accept().await.await.unwrap();
let connection = Arc::new(incoming_request.accept().await.unwrap());

// As you mentioned, here I spawn a new process-thread passing a ref of the connection.
 std::thread::spawn({
     let connection = Arc::clone(&connection);
     move || another_thread(connection)
 });

// So in this thread I use `tokio::select` to receive datagram.
loop {
   tokio::select! {
      // ....
     dgram = connection.receive_datagram() => {
            let dgram = dgram.unwrap();
            let str_data = std::str::from_utf8(&dgram).unwrap();
            println!("Received (dgram) '{str_data}' from client");
            connection.send_datagram(b"ACK").unwrap();
      }
}

// In this another thread, I am sending datagrams
fn another_thread(connection: Arc<Connection>) {
    loop {
        connection.send_datagram("DGRAM").unwrap();
        std::thread::sleep(std::time::Duration::from_secs(1));
    }
}
```

With this example, I was correctly able to receive datagrams (with a webclient) and send datagram concurrently.

**Comment by redoriental** [comment]
Because I need to interact between Rust and C++, for convenience, I converted the pointer of a Rust object to usize type using let connect_id: usize = unsafe { mem::transmute(&connection) };. When I need to invoke methods on Connection, I use let connect: Connection = unsafe { mem::transmute(connection_id) };. However, the connect object cannot invoke sendDatagram

**Comment by BiagioFesta** [comment]
Would you be able to produce a MRE (minimal reproducible example)?

I think you need dive a little bit; maybe isolating some part of your project step by step.

**Comment by redoriental** [comment]
I have already solved it using DashMap. Thank you for your help

**Comment by BiagioFesta** [comment]
Glad you were able to solve. But be careful with `unsafe` `transmute`. There is an high probability to generate undefined behavior
