### ISSUE TITLE
Access application closed reason as bytes/string

### ISSUE THREAD

**Issue by aecsocket** [BiagioFesta/wtransport#193]
There is the error variant `ConnectionError::ApplicationClosed(ApplicationClose)`, where `ApplicationClose` is
```rs
#[derive(Debug)]
pub struct ApplicationClose {
    code: VarInt,
    reason: Box<[u8]>,
}
```
But there is no way to access this `reason` directly, neither as a `&[u8]` nor as a `String`. This seems like an oversight, since accessing the application-layer disconnection reason is very useful for e.g. user-friendly disconnection messages. The only way to get this reason out right now is via the `Display` impl, which also adds some extra info like the error code, which I don't want.

There should be API like
```rs
fn code(&self) -> VarInt;

fn reason(&self) -> &[u8];
```
to access the components, or just make the fields of `ApplicationClose` public. Why do they have to be private anyway?

**Comment by BiagioFesta** [comment]
I missed that, Thank you
