### ISSUE TITLE
Session not terminating upon closed `CONNECT` stream

### ISSUE THREAD

**Issue by friendlymatthew** [BiagioFesta/wtransport#197]
The `wtransport` server is not terminating the session upon receiving a closed `CONNECT` stream.

According to the [WebTransport Internet Draft:](https://datatracker.ietf.org/doc/html/draft-ietf-webtrans-http3/#section-2)

> WebTransport sessions are initiated inside a given HTTP/3 connection by the client, who sends an extended `CONNECT` request. If the server accepts the request, a WebTransport session is established. The resulting stream will be further referred to as a `CONNECT` stream, and its `stream ID` is used to uniquely identify a given WebTransport session within the connection. The `ID` of the `CONNECT` stream that established a given WebTransport session will be further referred to as a `Session ID.`
> 
> A WebTransport session is terminated when the `CONNECT` stream that created it is closed.

Also under [5. Session Termination](https://datatracker.ietf.org/doc/html/draft-ietf-webtrans-http3/#section-5)

> A WebTransport session over HTTP/3 is considered terminated when either of the following conditions is met:
> 1. the CONNECT stream is closed, either cleanly or abruptly, on either side; or
> 2. a CLOSE_WEBTRANSPORT_SESSION capsule is either sent or received.

## Ruling out `quinn`

I added tracing logs in quinn to see the various Frames [processed and dispatched.](https://github.com/quinn-rs/quinn/blob/91be5467387ebbabffa884f6abb1b7663c8ffec4/quinn-proto/src/connection/mod.rs#L2652-L2876) Maybe the desired Frame wasn't being sent!

To verify this wasn't a problem on `quinn`'s end, I wrote a `JS` client in Chrome. That is:
```javascript
options = {
    "congestionControl":"low-latency",
    "requireUnreliable":true,
    "serverCertificateHashes": [
        {
            "algorithm":"sha-256",
            "value": "some_certificate_hash"
        }
    ]
}

webtransport = new WebTransport(url, options);
```

To close the session, I called:

```javascript
await webtransport.close();
```

When closing, I immediately receive a `Frame::Stream` from `quinn`:

<img width="758" alt="Screenshot 2024-08-07 at 9 44 20 AM" src="https://github.com/user-attachments/assets/822e8c90-213f-4fb7-8078-4c7ea111651a">

<br > 

This payload indicates that the `CONNECT` stream has been closed. This is because the `session_id` is 0 and `fin` is set to `true`.

Testing this behavior on Firefox, I received a `CLOSE_WEBTRANSPORT_SESSION` upon closing the `JS` client. This is fine since it is specified in the [Session Termination section of the internet draft.](https://datatracker.ietf.org/doc/html/draft-ietf-webtrans-http3/#section-5)

Our `wtransport` server is [similar to the implementation in examples.](https://github.com/BiagioFesta/wtransport/blob/master/wtransport/examples/full.rs) It seems other people are experiencing https://github.com/BiagioFesta/wtransport/issues/176#issuecomment-2094817279 @BiagioFesta hinted this may be a browser bug as well.

## Specifications
- `wtransport` version: 0.1.12
- Browsers tested:
        - Chrome (Version 127.0.6533.89)
        - (Firefox 129.0 (64-bit))

## Issues mentioned
https://github.com/BiagioFesta/wtransport/issues/176#issuecomment-2094817279

**Comment by BiagioFesta** [comment]
`SessionStream` (i.e., `CONNECT` stream) is not currently handled. See: https://github.com/BiagioFesta/wtransport/blob/22fdfb9aeb8b2a37067783d283872f4eea1b228a/wtransport/src/driver/mod.rs#L639

**Comment by BiagioFesta** [comment]
Please, it would be great. Definitely you can try a shot.

I started a branch: https://github.com/BiagioFesta/wtransport/tree/close-session-capsule (`close-session-capsule`) you might want to have a look.

In particular, the commit https://github.com/BiagioFesta/wtransport/commit/ae63af062a83c2eb0d97da5702a945cab504435e implementing the capsule protocol, with the webtransport close session capsule

**Comment by ktff** [comment]
Nice, I'll take a look.

**Comment by wegylexy** [comment]
![Image](https://github.com/user-attachments/assets/57ecc818-401a-4037-983b-9cb1cdd75099)
awaiting `connection.closed()` results in `connection timed out` instead of the expected `ApplicationClosed`

**Comment by wegylexy** [comment]
I figure that I only need to `tokio::select!` on `accept_uni`, `accept_bi`, and `receive_datagram` for `ApplicationClosed` to propagate as expected. However, the connection is not closed right after the driver reports the code and reason, but stays until idle timeout.

**Comment by wegylexy** [comment]
So, #8 is unresolved yet.

**Comment by ktff** [comment]
Can you provide a minimal example? Also what version of this crate are you using?

Based on the logs, the closure was detected and its propagation to local streams is right after it so I'm not sure what went wrong in your case.

**Comment by wegylexy** [comment]
@ktff If you look at the timestamps, the propagation took 30 seconds, which is exactly my configured `max_idle_timeout`. I tried different timeout durations, and confirmed it took such configured duration the following code to return the `ConnectionError::ApplicationClosed` after the underlying driver `debug!` log.

```rs
// server.rs
// following example server code but using latest commit on `master` branch
async fn handle_session_core(incoming: IncomingSession) -> Result<()> {
    let request = incoming.await?;
    let connection = request.accept().await?
    tokio::select! {
        biased; // <-- doesn't matter
        // closed = connection.closed() => { /* only TimedOut in this case, no ApplicationClosed */ }
        stream = connection.accept_bi() => { stream? }
        stream = connection.accept_uni() => { stream? }
        datagram = connection.receive_datagram() => { datagram? }
    }
}
// all 3 cases propagate the ConnectionError::ApplicationClosed after max_idle_timeout
```

```js
// client.js
const wt = new WebTransport(..., { requireUnreliable: true, congestionControl: "low-latency", ... });
// must wait until connected for closing code and reason to go through
wt.close(); // with code and reason or not
await wt.closed // if didn't wait til connected, promise is rejected immediately; server won't know
```

**Comment by wegylexy** [comment]
The problem is here: https://github.com/BiagioFesta/wtransport/blob/42ff2ddab5009476b0a69c48532eecd5128c70a1/wtransport/src/driver/mod.rs#L316 The server should not wait for an ack from the client when the client has initiated the close (by finishing this very `connect_stream`).

**Comment by ktff** [comment]
> The problem is here:
> 
> [wtransport/wtransport/src/driver/mod.rs](https://github.com/BiagioFesta/wtransport/blob/42ff2ddab5009476b0a69c48532eecd5128c70a1/wtransport/src/driver/mod.rs#L316)
> 
> Line 316 in [42ff2dd](/BiagioFesta/wtransport/commit/42ff2ddab5009476b0a69c48532eecd5128c70a1)
>  self.connect_stream.finish().await; 
> The server should not wait for an ack from the client when the client has initiated the close (by finishing this very `connect_stream`).

True, I missed there was a call to `stopped` in there. I'll open a PR which resets instead.
