### ISSUE TITLE
AsyncRead/AsyncWrite for datagrams

### ISSUE THREAD

**Issue by barafael** [BiagioFesta/wtransport#214]
Would it be a sensible API to expose sent/received datagrams by the async Read/Write traits?

This would enable using adapters to turn the Read/Write to streams, which would deliver the underlying messages on a best-effort base (dropping incomplete messages, at least).

**Comment by BiagioFesta** [comment]
Can you please elaborate that?

WebTransport datagrams are "framed" messages (while `AsyncRead` and `AsyncRead` are more about byte-streams). 

In `wtransport` a datagram is described by: https://docs.rs/wtransport/0.3.0/wtransport/datagram/struct.Datagram.html

**Comment by barafael** [comment]
Thanks, that clears it up, I appreciate your help!
