### ISSUE TITLE
The 0.3.0 release at crates.io is inconsistent with github

### ISSUE THREAD

**Issue by MOZGIII** [BiagioFesta/wtransport#215]
Looks like the release was packaged from a dirty tree.

On github we have this:

https://github.com/BiagioFesta/wtransport/blob/b55c6ba3ba019587f93ada0f56f351b93a45dfac/wtransport/src/driver/streams/mod.rs#L572-L574

but at the archive this:

```rust
            quinn::ReadError::ConnectionLost(error) => {
                dbg!(error);
                todo!();
            }
```

So, the `xwt` test suite fails :D

---

I suggest yanking 0.3.0 and publishing 0.3.1 from a clean tree asap.

**Comment by BiagioFesta** [comment]
That was very inconvenient. I did not know cargo publish unstaged files, sorry about that.

Thank you for the prompt report, I am going to fix as suggested

**Comment by BiagioFesta** [comment]
Fixed in: https://github.com/BiagioFesta/wtransport/commit/cde28dae2302efb9bcb0c1bce36b9edddb2acb17
Release in: https://github.com/BiagioFesta/wtransport/releases/tag/0.3.1
