### ISSUE TITLE
Error when executing example to open a bidirectional stream

### ISSUE THREAD

**Issue by bhbs** [BiagioFesta/wtransport#219]
## Error

<img width="378" alt="image" src="https://github.com/user-attachments/assets/b73e1f5c-12a6-4bc0-8996-03d010109a2a">

## Reproduction

```sh
cargo run --example full
```

1. Click `Connect`
2. Select `Open a bidirectional stream`
3. Click `Send data`

**Comment by BiagioFesta** [comment]
What browser/version? (I cannot reproduce with `Firefox, 129.0` and `Google Chrome, 128.0.6613.113`

**Comment by bhbs** [comment]
Google Chrome / 128.0.6613.138（arm64）👍
