### ISSUE TITLE
Allow cloning `Connection`s

### ISSUE THREAD

**Issue by aecsocket** [BiagioFesta/wtransport#225]
Currently `Connection` is defined as
```rs
pub struct Connection {
    quic_connection: quinn::Connection,
    driver: Driver,
    session_id: SessionId,
}
```

The `quinn::Connection` can already be cloned, as it's just a wrapper around an `Arc`:
```rs
#[derive(Debug, Clone)]
pub struct Connection(ConnectionRef);

#[derive(Debug)]
pub(crate) struct ConnectionRef(Arc<ConnectionInner>);
```

The `SessionId` is already `Clone + Copy`.

The `Driver` is not Clone, but this could be turned into an `Arc<Driver>` similar to how `quinn::Connection` is already used.

Being able to clone a `wtransport::Connection` is useful for the same reason that it's useful to clone a `quinn::Connection`. In my use case, I have an async task that owns a `Connection`, and I want to:
- spawn a new task for sending out data along it
- spawn a new task for receiving data along it
- have access to the connection in the original task to `close `it

Right now I have to manually `Arc` the connection, which seems redundant since the `quinn::Connection` is already `Arc`'d, and the `SessionId` is trivial copy. It would be useful to not have to `Arc` it myself and just pass clones.

**Comment by BiagioFesta** [comment]
Yeah, let's do it
