### ISSUE TITLE
Max frame size is too restrictive

### ISSUE THREAD

**Issue by UkoeHB** [BiagioFesta/wtransport#243]
Currently there is a hard-coded limit `Frame::MAX_PARSE_PAYLOAD_ALLOWED = 4096`.

This is causing problems for my application, where I am passing a large blob via the connection request URI in order to pre-validate connections (I use `SessionRequest::path` to extract it). The blob is ~1100 bytes but serialized as JSON the URI ends up at 5982 bytes. The app works fine with `h3` but I'd like to use this crate instead.

Note that I'm using the URI instead of a header because browsers don't let you set custom headers (or at least web_sys doesn't). Also I'm using the URI instead of a post-connection message because A) I want to terminate invalid connections ASAP, and B) webtransport datagrams are unreliable so I'd need to open a stream just to send one connection request.

My ideal solution would be to loosen the max size for connection requests, and leave it in place for everything else.

**Comment by UkoeHB** [comment]
According to [this](https://stackoverflow.com/questions/686217/maximum-on-http-header-values), 4kB is an expected lower limit for HTTP headers. So it seems I need to fix my implementation and this crate is not seriously out of line (although 8kB is more standard).

**Comment by UkoeHB** [comment]
I solved my own problem. Use the `urlencoding` crate to serialize bytes for a URL query, and if using `url::Url`, use `.set_url` instead of adding query pairs (since `url` has its own serialization method for strings that doesn't layer on top of `urlencoding` properly).

**Comment by BiagioFesta** [comment]
Sorry, I was out for the Christmas holiday and couldn’t reply promptly.

I’m glad to see you were able to work around this, and I agree with the limits on HTTP headers. In fact, `wtransport` pre-allocates the payload frame, so this limit is important for security: https://github.com/BiagioFesta/wtransport/issues/68

That said, I think this case could still be useful. Perhaps we could consider introducing a setting for this, allowing the limit to be customized according to the specific application domain.
