### ISSUE TITLE
Expose maxDatagramSize property

### ISSUE THREAD

**Issue by MatrixDev** [BiagioFesta/wtransport#29]
As title says.

This property is almost mandatory if larger packets are needed to be sent (like video frames) which might be larger than MTU. This will result in an error.

WebTransport Docs:
https://developer.mozilla.org/en-US/docs/Web/API/WebTransportDatagramDuplexStream/maxDatagramSize

This is why we need it:
```rust
/// Transmit `data` as an unreliable, unordered application datagram
///
/// Application datagrams are a low-level primitive. They may be lost or delivered out of order,
/// and `data` must both fit inside a single QUIC packet and be smaller than the maximum
/// dictated by the peer.
pub fn send_datagram(&self, data: Bytes) -> Result<(), SendDatagramError>
```

This is how to get max datagram size in quinn:
```rust
/// Compute the maximum size of datagrams that may passed to `send_datagram`
///
/// Returns `None` if datagrams are unsupported by the peer or disabled locally.
///
/// This may change over the lifetime of a connection according to variation in the path MTU
/// estimate. The peer can also enforce an arbitrarily small fixed limit, but if the peer's
/// limit is large this is guaranteed to be a little over a kilobyte at minimum.
///
/// Not necessarily the maximum size of received datagrams.
pub fn max_size(&self) -> Option<usize>
```

**Comment by BiagioFesta** [comment]
Thank you for your feedback, and I agree with having this interface.

We recently merged this on `master`: https://github.com/BiagioFesta/wtransport/commit/fd9f75c5815061c15ac4288cc6ca92d923b2ac9c that exposes it

**Comment by BiagioFesta** [comment]
I also should add a few settings for MTU and queues sizes from QUIC transport. Anyway, this is out of the scope of this issue. I am going to close this as solved.
