### ISSUE TITLE
Expose more configuration options

### ISSUE THREAD

**Issue by MOZGIII** [BiagioFesta/wtransport#34]
It would be great to have more configuration options available for both client and server.

I am in particular looking for more options to configure the certificates (i.e. on the server we need to rotate them), the low-level access to rustls configs (for things like SSLKEYLOGFILE), the ability to tweak the underlying socket.
Also, a way to do a custom DNS resolution would be nice (like with https://github.com/MOZGIII/hyper-system-resolver sometimes I want to hint which IP family I prefer/want to force A/AAAA records).

**Comment by BiagioFesta** [comment]
For now, maybe you can workaround with: https://github.com/BiagioFesta/wtransport/commit/57d2fc852a5ee99497438c3a4ea5f5e958ff7e1a

**Comment by MOZGIII** [comment]
Perfect!

**Comment by MOZGIII** [comment]
This will do, I'm closing #48.

**Comment by BiagioFesta** [comment]
What about https://github.com/BiagioFesta/wtransport/pull/80 ?

**Comment by MOZGIII** [comment]
Even better!
