### ISSUE TITLE
A call to connection.closed() never seems to resolve

### ISSUE THREAD

**Issue by bugnano** [BiagioFesta/wtransport#37]
In my server configuration I poll for `connection.closed()`, which should resolve when the remote end of the connection is closed.
Now, I tried to connect from https://webtransport.day , and all the connection and data sending/receiving went OK.
After closing the browser tab, I expect the `connection.closed()` call to resolve, but it doesn't (at least not in the 5 minutes that I waited).

I also tried to configure the server config setting `config_builder.max_idle_timeout(Some(Duration::from_secs(30)))` and waited for a timeout to happen.
Just to be sure, I also lowered the number to 2, but nothing, the `connection.closed()` call never seems to resolve.

**Comment by bugnano** [comment]
Relevant code snippet:
```rust
    loop {
        tokio::select! {
            dgram = connection.receive_datagram() => {
                let dgram = dgram?;
                let str_data = std::str::from_utf8(&dgram)?;
                trace!("Received (dgram) '{str_data}' from client");
            }
            _ = connection.closed() => {
                debug!("Connection closed");

                return Ok(());
            }
        }
    }

```

**Comment by BiagioFesta** [comment]
Is the log line `debug!("Connection closed");` not printed at all?

I am not able to reproduce (used the server-example, that is, `examples/server.rs`, with your modification)

**Comment by bugnano** [comment]
OK, so maybe this is a problem with Firefox after all.
It looks like Firefox keeps the connection open even if I close the tab, but if I close Firefox, then the "Connection closed" message gets printed.
