### ISSUE TITLE
Feature request: Expose the HTTP headers as a HashMap

### ISSUE THREAD

**Issue by bugnano** [BiagioFesta/wtransport#38]
It would be nice to have exposed the underlying HashMap of the Headers struct, instead of having to call `session_request.get(header)` or `session_request.headers().get(header)` for every header I'm interested in.
I tried accessing `session_request.headers().0` but it's a private field.

**Comment by BiagioFesta** [comment]
I think exposing the underlying data structure violates the encapsulation. 

What is the use case you are thinking of?
Maybe we could just expose the behavior instead of data (e.g., function methods).

**Comment by bugnano** [comment]
My use case is that I'm writing an Elixir binding for this library (check it out at: https://github.com/bugnano/wtransport-elixir -- maybe you can also advertise it in the readme 😉), so I wanted to expose the headers to Elixir as a mapping.

**Comment by BiagioFesta** [comment]
I like the idea to avoid exposing `Headers` from wtransport-proto. So maybe exposing the hashmap might be a solution for now.

Please have a look at: https://github.com/BiagioFesta/wtransport/pull/39, if that makes sense to you.

> maybe you can also advertise it in the readme 
Feel free to open a PR modifying the README.md with that

**Comment by bugnano** [comment]
Yes, #39 works perfectly, thank you 🙂
