### ISSUE TITLE
It's already great, but there are still some questions, such as whether you can provide the closing events for session and stream.

### ISSUE THREAD

**Issue by redoriental** [BiagioFesta/wtransport#4]

**Comment by BiagioFesta** [comment]
Thanks for the feedback.

I agree. As mentioned in previous discussions, the API is not yet fully completed. Initially, my focus was on creating something functional.

[`Connection`](https://docs.rs/wtransport/0.1.0/wtransport/struct.Connection.html) and stream handlers (i.e., [`SendStream`](https://docs.rs/wtransport/0.1.0/wtransport/struct.SendStream.html) and [`RecvStream`](https://docs.rs/wtransport/0.1.0/wtransport/struct.RecvStream.html)) already have an implicit method for closing. In fact, stream and connection are "automatically" closed when the object is dropped.

Additionally, the "*peer connection closed*" event is already captured when awaiting on other connection events.

Having said that, I agree that having a convenient method to access those events would be beneficial. The underlying QUIC library (`quinn`) already provides such functionality, so it should be relatively easy to expose those features at the WebTransport layer.

I will prioritize working on this as soon as possible.

**Comment by redoriental** [comment]
Place sendStream and receiveStream inside a structure with a unique u64 ID. The structure should also have a bool type to determine if it is a bidirectional stream. When the stream triggers the close method, only the ID of the closed stream needs to be provided to the user. The same applies to the session, where a sessionId of type u64 is set.

**Comment by redoriental** [comment]
I believe in you and your abilities!

**Comment by redoriental** [comment]
Thank you, it turns out that I didn't add the 'lib' directory to the environment variables. Previously, I only added the 'bin' directory.

**Comment by BiagioFesta** [comment]
Closing this issue, as
* Close event on connection: https://github.com/BiagioFesta/wtransport/commit/d5f25fc468411b814e3157266859d1284841ffef
* Stream IDs: https://github.com/BiagioFesta/wtransport/commit/f68f4403e310c3a748384c8f10eebf4505f277d2
