### ISSUE TITLE
Chrome does not connect to the wtransport server

### ISSUE THREAD

**Issue by MOZGIII** [BiagioFesta/wtransport#43]
Discovered this issue recently.

Most likely caused by this: https://source.chromium.org/chromium/chromium/src/+/refs/heads/main:net/third_party/quiche/src/quiche/quic/core/http/quic_spdy_session.cc;l=1303;drc=5cb22f99522203e552ff9de07dbc895f26a96dd4;bpv=1;bpt=1

(see https://source.chromium.org/chromium/chromium/src/+/refs/heads/main:net/third_party/quiche/src/quiche/quic/core/http/quic_spdy_session.h;l=687;drc=5cb22f99522203e552ff9de07dbc895f26a96dd4;bpv=1;bpt=1)

When `0xc671706a` setting is activated, it actually enables draft-07 instead of draft-02 which would otherwise be the max version; this in turn causes the version negotiation at the Chrome side to select draft-07, which wtransport doesn't support (until #42).

As can be seen from the link above, at Chrome the `0xc671706a` corresponds to `SETTINGS_WEBTRANS_MAX_SESSIONS_DRAFT07` - with `DRAFT07` in the name, so this is a hint that it will trigger `draft07`.

With all this, Chrome fails the connection with the following error: `WebTransport over HTTP/3 version draft-07 and beyond requires the RFC version of HTTP datagrams`. It suggests we need to complete #42, or use `draft-02` and avoid touching `draft-07`. Or there might be a simple missing setting for HTTP/3 datagrams or sth like that - I didn't check that yet.

**Comment by BiagioFesta** [comment]
Thank you for the report and the investigation!

With GChrome `Version 115.0.5790.110`, the browser sends the following header request:

```
{
    ":path": "/",
    "origin": "https://webtransport.day",
    ":protocol": "webtransport",
    "sec-webtransport-http3-draft02": "1",
    ":method": "CONNECT",
    ":authority": "localhost:4433",
    ":scheme": "https",
}
```

where it states ` "sec-webtransport-http3-draft02": "1"`.

What browser version are you testing?

**Comment by MOZGIII** [comment]
I was trying stable Chrome (115), Dev Chrome (117), latest Chromium.
Basically, stumbled upon this issue, but then got stuck until I went and read the source code. It it nice to have open source all the way across the stack.

As far as I can tell from reading the source, Chrome will send `"sec-webtransport-http3-draft02": "1"` even when it uses `draft-07`. There are no checks for the protocol version where they add this header.

**Comment by MOZGIII** [comment]
Side note: I discovered a new flag `--webtransport-developer-mode` that replaces `--origin-to-force-quic-on=localhost:4433` and is more secure in a way that I applied to WebTransport connections only.

**Comment by BiagioFesta** [comment]
I was able to reproduce with `Version 117.0.5911.2` (Dev version)
I was not able to reproduce with `Version 115.0.5790.110` (Stable version)

**Comment by BiagioFesta** [comment]
Now it should work (`master` branch for now) even with Chrome Dev version. Please let me know if that worked

**Comment by MOZGIII** [comment]
All good, works!

As I side note, I'm getting the console prints of `QQ RecvStream` with `master` branch now, not sure where they come from, but it started when I switched to `master`.

**Comment by BiagioFesta** [comment]
Uhm? Can you please investigate on that (in case open a dedicate issue)? What do you mean you get console prints?

**Comment by MOZGIII** [comment]
<img width="698" alt="image" src="https://github.com/BiagioFesta/wtransport/assets/265507/5a6b00f8-6fa7-4088-b178-1755d705fe43">
I'll create an issue
