### ISSUE TITLE
Seems like there is no timeout functionality

### ISSUE THREAD

**Issue by redoriental** [BiagioFesta/wtransport#5]

**Comment by redoriental** [comment]
I think you need to add the following functionalities:

Timeout setting.
Path retrieval, like extracting the '/test' string from 'https://redoriental.top:10001/test'.
Parameter extraction from the path, for example, from 'https://redoriental.top:10001/test?a=b&b=c', I need to extract a map {'a'='b', 'b'='c'}.
I need to retrieve the remote IP address and port.

**Comment by redoriental** [comment]
When using 'wtransport' as the server and transmitting video streams using WebTransport on the frontend, I often encounter timeouts due to slow camera opening, which causes the program to stop.

**Comment by redoriental** [comment]
Can't the underlying layer of 'Quinn' implement the functionality of retrieving the path?

**Comment by redoriental** [comment]
If it could be done that way, it would be even better. You can provide the user with a 'path' parameter in the 'connection' after 'accept' so that the user can handle it. It would be too cumbersome if it had to be done in the traditional HTTP manner.

**Comment by BiagioFesta** [comment]
Implemented and just merged in master
