### ISSUE TITLE
Expose datagram content as Bytes?

### ISSUE THREAD

**Issue by rom1v** [BiagioFesta/wtransport#51]
Thank you for your library, very useful for my experiments with `WebTransport` :+1:

A [`Datagram`](https://docs.rs/wtransport/0.1.4/wtransport/datagram/struct.Datagram.html) internally uses a `Bytes` instance, but only exposes a [`Deref<Target=[u8]>`](https://docs.rs/wtransport/0.1.4/wtransport/datagram/struct.Datagram.html#deref-methods-%5Bu8%5D).

On one hand, it may be useful for the implementation because it can change from `Bytes` to something else internally without changing the API. But on the other hand, the caller is forced to copy the content, even if it uses `Bytes`:

```rust
let datagram = conn.receive_datagram().await?;
let bytes = Bytes::copy_from_slice(&datagram);
```

Since `Bytes` is very common, and is also exposed in the quinn API, it might make sense to expose the payload as a `Bytes` instance. Something like this:

```diff
diff --git a/wtransport/src/datagram.rs b/wtransport/src/datagram.rs
index f2cd4dc..419bcab 100644
--- a/wtransport/src/datagram.rs
+++ b/wtransport/src/datagram.rs
@@ -57,6 +57,11 @@ impl Datagram {
     pub(crate) fn into_quic_bytes(self) -> Bytes {
         self.quic_dgram
     }
+
+    /// Return the payload
+    pub fn payload(&self) -> Bytes {
+        self.quic_dgram.slice(self.payload_offset..)
+    }
 }
 
 impl Deref for Datagram {
```

This would allow to avoid a whole copy for each datagram received.

What do you think?

**Comment by BiagioFesta** [comment]
> On one hand, it may be useful for the implementation because it can change from Bytes to something else internally without changing the API.

You got the right point. 
Being at the early stage of releasing, I am trying to be slightly more conservative on the API of `wtransport`, also with re-export external dependencies.

By doing so, I think it allows the library to grow reflecting real needs on feedback like yours (thank you, btw). 

Having said that,

> Since Bytes is very common,

I agree on this point and, thus, I think it might be worth it to expose `Bytes` (also considering it practically comes for free, as you mentioned). I am going to open a PR as you suggested.

Off topic: I still don't completely understand why `bytes` crates does not implement something that can leverage the borrowing system of rust. For instance with lifetimes for having a memory view to an existing slice, `Bytes<'a>::from_ref(&buffer)`
