### ISSUE TITLE
Implement Debug for all types

### ISSUE THREAD

**Issue by rom1v** [BiagioFesta/wtransport#58]
Would it be possible to add:

```rust
#[derive(Debug)]
```

for all wtransport API types?

Currently, embedding a wtransport type in another structure prevents to automatically derive `Debug` for our own types.

For example, quinn implements `Debug` for `SendStream` (and others): https://docs.rs/quinn/latest/quinn/struct.SendStream.html#impl-Debug-for-SendStream

**Comment by BiagioFesta** [comment]
Sure. If you wish feel free to open a PR; otherwise I will soon
