### ISSUE TITLE
When the frontend closes the connection, it will trigger the connection.receive_datagram() method once

### ISSUE THREAD

**Issue by redoriental** [BiagioFesta/wtransport#8]

**Comment by BiagioFesta** [comment]
[`receive_datagram`](https://github.com/BiagioFesta/wtransport/blob/master/wtransport/src/connection.rs#LL170C1-L170C78) awaits for receiving the next datagram for the connection.

If the connection is closed, then the `async` function will returns but with an error `Err`.

This is expected

**Comment by redoriental** [comment]
My frontend closes the 'webtransport', and it takes a long 30 seconds for the backend to detect that the 'connection' has been closed.

**Comment by BiagioFesta** [comment]
The transport layer of this library currently sets a timeout of *10 seconds*.

It means that by using the [`Connection`](https://docs.rs/wtransport/latest/wtransport/struct.Connection.html) of this library, the connection will be detected as closed (`Timed-Out`) in the *worst case*.

**Worst-case** means: your front-end interrupts the connection without a "graceful shutdown". For instance, by closing the UDP socket without sending a proper quic-`CLOSE` frame.

If your front-end properly signals the end of connection, the connection will ends immediately as soon as the udp packet arrives on the endpoint.

**Comment by redoriental** [comment]
I understand what you mean. This is also due to the underlying limitations of 'WebTransport,' as it lacks a built-in heartbeat mechanism like WebSocket. Consequently, it requires an active close action to initiate the closure.

**Comment by redoriental** [comment]
I believe that future 'WebTransport' implementations will include a heartbeat mechanism.

**Comment by BiagioFesta** [comment]
Unfortunately, this requires time.

I am working hard on this, but it is more a personal project for now and it takes time :)

**Comment by redoriental** [comment]
Don't worry, I believe that in the future, there will be a large number of developers collaborating with you, including myself. However, I am currently attending university, making it difficult for me to fully dedicate myself to this project.

**Comment by redoriental** [comment]
How is the progress?

**Comment by redoriental** [comment]
How is the progress?

**Comment by BiagioFesta** [comment]
New release is out.

It includes:
* Transport settings for `keep_alive` PING.
* Transport settings for timeout.
* New `SessionRequest` to access HTTP request and decide whether accept or reject

I am closing this issue.
