### ISSUE TITLE
Certificate::load() should be async

### ISSUE THREAD

**Issue by rom1v** [BiagioFesta/wtransport#81]
[`Certificate::load()`](https://docs.rs/wtransport/0.1.7/wtransport/tls/struct.Certificate.html#method.load) is a blocking function (it calls `std::fs::read()` internally).

I think it should be an `async` function, using for example `tokio::fs::read()`, so that certificates may be loaded without blocking the event loop.

**Comment by BiagioFesta** [comment]
Considering `Certificate` is pretty specific for this crate (not having general purpose methods), I totally agree
