### ISSUE TITLE
Axum integration

### ISSUE THREAD

**Issue by gabelluardo** [BiagioFesta/wtransport#85]
What is the best/easiest way to integrate this in a REST API server based on Axum?

**Comment by BiagioFesta** [comment]
Have you something in mind, in particular?

WebTransport is an end-to-end communication protocol, given its generic nature it can serve in different purpose.

For instance, an application might serve an webtransport client via HTTP/Axum communicating with a webtransport server.

It is still a development branch I am working on, but, if you want to, you could have a look at `example-full` branch of this repo, and check the `wtransport/examples/fuill.rs`: https://github.com/BiagioFesta/wtransport/blob/example-full/wtransport/examples/full.rs

**Still development branch**, but in theory it should already work:
```
git clone -b example-full --depth=1 https://github.com/BiagioFesta/wtransport.git && cd wtransport && cargo run --example full
```

This launches google-chrome, connecting a local axum server, serving a webtransport client that exchange textual messages.

**Comment by BiagioFesta** [comment]
The development branch has been merged on `master`.

So you can just run the `full` example with:
```
cargo new --example full
```

[More info here](https://github.com/BiagioFesta/wtransport#getting-started)

**Comment by gabelluardo** [comment]
Thanks, that's exactly what I was looking for!

**Comment by BiagioFesta** [comment]
Closing this issue as solved
